### ISSUE TITLE
[Bug]无法运行模型（仅当作一个语言模型使用）

### ISSUE THREAD

**Issue by homo11451419** [Moemu/Muice-Chatbot#10]
### 描述此Bug

原版ChatGLM2可以使用，但使用这个微调模型会报错

### 控制台输出
Traceback (most recent call last):
  File "D:\chatglm\web_demo.py", line 6, in <module>
    tokenizer = AutoTokenizer.from_pretrained("D:\chatglm\models\Muice", trust_remote_code=True)
  File "D:\Programs Files\Python\Python311\Lib\site-packages\transformers\models\auto\tokenization_auto.py", line 678, in from_pretrained
    return tokenizer_class.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
  File "D:\Programs Files\Python\Python311\Lib\site-packages\transformers\tokenization_utils_base.py", line 1825, in from_pretrained
    return cls._from_pretrained(
  File "D:\Programs Files\Python\Python311\Lib\site-packages\transformers\tokenization_utils_base.py", line 1988, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "C:\Users\ZhaoYunFeng/.cache\huggingface\modules\transformers_modules\Muice\tokenization_chatglm.py", line 69, in __init__
    super().__init__(padding_side=padding_side, clean_up_tokenization_spaces=False, **kwargs)
TypeError: transformers.tokenization_utils.PreTrainedTokenizer.__init__() got multiple values for keyword argument 'clean_up_tokenization_spaces'

### 复现该Bug的操作

tokenizer = AutoTokenizer.from_pretrained("D:\chatglm\models\Muice", trust_remote_code=True)
model = AutoModel.from_pretrained("D:\chatglm\models\Muice", trust_remote_code=True).cuda()

**Comment by Moemu** [comment]
您似乎直接加载了经过P-tuningV2微调后的模型，因此会引发报错。
以官方模型加载方法先加载原始模型，再加载微调后的模型来解决此问题。
```python
    def __init__(self,chatglm_model_path:str, pt_model_path:str):
        device = torch.device(0)
        model_path = chatglm_model_path
        config = AutoConfig.from_pretrained(model_path, trust_remote_code=True, pre_seq_len=128)
        self.tokenizer = AutoTokenizer.from_pretrained(model_path, trust_remote_code=True)
        model = AutoModel.from_pretrained(model_path, config=config, trust_remote_code=True).half().to(device)
        prefix_state_dict = torch.load(os.path.join(pt_model_path, "pytorch_model.bin"))
        new_prefix_state_dict = {}
        for k, v in prefix_state_dict.items():
            if k.startswith("transformer.prefix_encoder."):
                new_prefix_state_dict[k[len("transformer.prefix_encoder."):]] = v
        model.transformer.prefix_encoder.load_state_dict(new_prefix_state_dict)
        model = model.half().cuda()
        model.transformer.prefix_encoder.float()
        self.model = model.eval()
```

**Comment by homo11451419** [comment]
> 您似乎直接加载了经过P-tuningV2微调后的模型，因此会引发报错。 以官方模型加载方法先加载原始模型，再加载微调后的模型来解决此问题。
> 
> ```python
>     def __init__(self,chatglm_model_path:str, pt_model_path:str):
>         device = torch.device(0)
>         model_path = chatglm_model_path
>         config = AutoConfig.from_pretrained(model_path, trust_remote_code=True, pre_seq_len=128)
>         self.tokenizer = AutoTokenizer.from_pretrained(model_path, trust_remote_code=True)
>         model = AutoModel.from_pretrained(model_path, config=config, trust_remote_code=True).half().to(device)
>         prefix_state_dict = torch.load(os.path.join(pt_model_path, "pytorch_model.bin"))
>         new_prefix_state_dict = {}
>         for k, v in prefix_state_dict.items():
>             if k.startswith("transformer.prefix_encoder."):
>                 new_prefix_state_dict[k[len("transformer.prefix_encoder."):]] = v
>         model.transformer.prefix_encoder.load_state_dict(new_prefix_state_dict)
>         model = model.half().cuda()
>         model.transformer.prefix_encoder.float()
>         self.model = model.eval()
> ```

额……代码没看懂（doge
官方的代码：
```python
from transformers import AutoModel, AutoTokenizer
import gradio as gr
import mdtex2html
from utils import load_model_on_gpus

tokenizer = AutoTokenizer.from_pretrained("THUDM/chatglm2-6b", trust_remote_code=True)
model = AutoModel.from_pretrained("THUDM/chatglm2-6b", trust_remote_code=True).cuda()
# 多显卡支持，使用下面两行代替上面一行，将num_gpus改为你实际的显卡数量
# from utils import load_model_on_gpus
# model = load_model_on_gpus("THUDM/chatglm2-6b", num_gpus=2)
model = model.eval()

"""Override Chatbot.postprocess"""


def postprocess(self, y):
    if y is None:
        return []
    for i, (message, response) in enumerate(y):
        y[i] = (
            None if message is None else mdtex2html.convert((message)),
            None if response is None else mdtex2html.convert(response),
        )
    return y


gr.Chatbot.postprocess = postprocess


def parse_text(text):
    """copy from https://github.com/GaiZhenbiao/ChuanhuChatGPT/"""
    lines = text.split("\n")
    lines = [line for line in lines if line != ""]
    count = 0
    for i, line in enumerate(lines):
        if "```" in line:
            count += 1
            items = line.split('`')
            if count % 2 == 1:
                lines[i] = f'<pre><code class="language-{items[-1]}">'
            else:
                lines[i] = f'<br></code></pre>'
        else:
            if i > 0:
                if count % 2 == 1:
                    line = line.replace("`", "\`")
                    line = line.replace("<", "&lt;")
                    line = line.replace(">", "&gt;")
                    line = line.replace(" ", "&nbsp;")
                    line = line.replace("*", "&ast;")
                    line = line.replace("_", "&lowbar;")
                    line = line.replace("-", "&#45;")
                    line = line.replace(".", "&#46;")
                    line = line.replace("!", "&#33;")
                    line = line.replace("(", "&#40;")
                    line = line.replace(")", "&#41;")
                    line = line.replace("$", "&#36;")
                lines[i] = "<br>"+line
    text = "".join(lines)
    return text


def predict(input, chatbot, max_length, top_p, temperature, history, past_key_values):
    chatbot.append((parse_text(input), ""))
    for response, history, past_key_values in model.stream_chat(tokenizer, input, history, past_key_values=past_key_values,
                                                                return_past_key_values=True,
                                                                max_length=max_length, top_p=top_p,
                                                                temperature=temperature):
        chatbot[-1] = (parse_text(input), parse_text(response))

        yield chatbot, history, past_key_values


def reset_user_input():
    return gr.update(value='')


def reset_state():
    return [], [], None


with gr.Blocks() as demo:
    gr.HTML("""<h1 align="center">ChatGLM2-6B</h1>""")

    chatbot = gr.Chatbot()
    with gr.Row():
        with gr.Column(scale=4):
            with gr.Column(scale=12):
                user_input = gr.Textbox(show_label=False, placeholder="Input...", lines=10).style(
                    container=False)
            with gr.Column(min_width=32, scale=1):
                submitBtn = gr.Button("Submit", variant="primary")
        with gr.Column(scale=1):
            emptyBtn = gr.Button("Clear History")
            max_length = gr.Slider(0, 32768, value=8192, step=1.0, label="Maximum length", interactive=True)
            top_p = gr.Slider(0, 1, value=0.8, step=0.01, label="Top P", interactive=True)
            temperature = gr.Slider(0, 1, value=0.95, step=0.01, label="Temperature", interactive=True)

    history = gr.State([])
    past_key_values = gr.State(None)

    submitBtn.click(predict, [user_input, chatbot, max_length, top_p, temperature, history, past_key_values],
                    [chatbot, history, past_key_values], show_progress=True)
    submitBtn.click(reset_user_input, [], [user_input])

    emptyBtn.click(reset_state, outputs=[chatbot, history, past_key_values], show_progress=True)

demo.queue().launch(share=False, inbrowser=True)```
如何修改？

**Comment by Moemu** [comment]
以下给出了一个示例函数，其中函数期望传入`chatglm_model_path`与`pt_model_path`变量，它们分别代表chatglm初始模型路径和微调后的模型路径
```python
    def load_model(chatglm_model_path:str, pt_model_path:str):
        device = torch.device(0)
        model_path = chatglm_model_path
        config = AutoConfig.from_pretrained(model_path, trust_remote_code=True, pre_seq_len=128)
        tokenizer = AutoTokenizer.from_pretrained(model_path, trust_remote_code=True)
        model = AutoModel.from_pretrained(model_path, config=config, trust_remote_code=True).half().to(device)
        prefix_state_dict = torch.load(os.path.join(pt_model_path, "pytorch_model.bin"))
        new_prefix_state_dict = {}
        for k, v in prefix_state_dict.items():
            if k.startswith("transformer.prefix_encoder."):
                new_prefix_state_dict[k[len("transformer.prefix_encoder."):]] = v
        model.transformer.prefix_encoder.load_state_dict(new_prefix_state_dict)
        model = model.half().cuda()
        model.transformer.prefix_encoder.float()
        model = model.eval()
        return model
```
For example:
```python
model = load_model('./chatglm2-6b','./Muice')
model.ask('hi')
```

**Comment by homo11451419** [comment]
```python>>> %Run web_demo_Muice.py
Traceback (most recent call last):
  File "D:\chatglm\web_demo_Muice.py", line 23, in <module>
    model = load_model('./chatglm2-6b','./Muice')
  File "D:\chatglm\web_demo_Muice.py", line 10, in load_model
    config = AutoConfig.from_pretrained(model_path, trust_remote_code=True, pre_seq_len=128)
  File "D:\Programs Files\Python\Python311\Lib\site-packages\transformers\models\auto\configuration_auto.py", line 953, in from_pretrained
    config_class = get_class_from_dynamic_module(class_ref, pretrained_model_name_or_path, **kwargs)
  File "D:\Programs Files\Python\Python311\Lib\site-packages\transformers\dynamic_module_utils.py", line 443, in get_class_from_dynamic_module
    return get_class_in_module(class_name, final_module.replace(".py", ""))
  File "D:\Programs Files\Python\Python311\Lib\site-packages\transformers\dynamic_module_utils.py", line 164, in get_class_in_module
    module = importlib.import_module(module_path)
  File "D:\Programs Files\Python\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'transformers_modules.'```
此时我的be like:（省流：妈妈生的）

**Comment by Moemu** [comment]
尝试使用绝对路径更改`load_model`函数中的参数路径，For example: `model = load_model('D:\chatglm\models\chatglm2-6b','.D:\chatglm\models\Muice)`

**Comment by homo11451419** [comment]
妈 妈 生 的 * 1 1 4 5 1 4
```python
import torch
from transformers import AutoModel, AutoTokenizer,AutoConfig
import gradio as gr
import mdtex2html
from utils import load_model_on_gpus
import os

def load_model(chatglm_model_path:str, pt_model_path:str):
    device = torch.device(0)
    model_path = chatglm_model_path
    config = AutoConfig.from_pretrained(model_path, trust_remote_code=True, pre_seq_len=128)
    tokenizer = AutoTokenizer.from_pretrained(model_path, trust_remote_code=True)
    model = AutoModel.from_pretrained(model_path, config=config, trust_remote_code=True).half().to(device)
    prefix_state_dict = torch.load(os.path.join(pt_model_path, "pytorch_model.bin"))
    new_prefix_state_dict = {}
    for k, v in prefix_state_dict.items():
        if k.startswith("transformer.prefix_encoder."):
            new_prefix_state_dict[k[len("transformer.prefix_encoder."):]] = v
    model.transformer.prefix_encoder.load_state_dict(new_prefix_state_dict)
    model = model.half().cuda()
    model.transformer.prefix_encoder.float()
    model = model.eval()
    return model
model = load_model('D:\chatglm\models\chatglm2-6b','D:\chatglm\Muice')

def postprocess(self, y):
    if y is None:
        return []
    for i, (message, response) in enumerate(y):
        y[i] = (
            None if message is None else mdtex2html.convert((message)),
            None if response is None else mdtex2html.convert(response),
        )
    return y


gr.Chatbot.postprocess = postprocess


def parse_text(text):
    """copy from https://github.com/GaiZhenbiao/ChuanhuChatGPT/"""
    lines = text.split("\n")
    lines = [line for line in lines if line != ""]
    count = 0
    for i, line in enumerate(lines):
        if "```" in line:
            count += 1
            items = line.split('`')
            if count % 2 == 1:
                lines[i] = f'<pre><code class="language-{items[-1]}">'
            else:
                lines[i] = f'<br></code></pre>'
        else:
            if i > 0:
                if count % 2 == 1:
                    line = line.replace("`", "\`")
                    line = line.replace("<", "&lt;")
                    line = line.replace(">", "&gt;")
                    line = line.replace(" ", "&nbsp;")
                    line = line.replace("*", "&ast;")
                    line = line.replace("_", "&lowbar;")
                    line = line.replace("-", "&#45;")
                    line = line.replace(".", "&#46;")
                    line = line.replace("!", "&#33;")
                    line = line.replace("(", "&#40;")
                    line = line.replace(")", "&#41;")
                    line = line.replace("$", "&#36;")
                lines[i] = "<br>"+line
    text = "".join(lines)
    return text


def predict(input, chatbot, max_length, top_p, temperature, history, past_key_values):
    chatbot.append((parse_text(input), ""))
    for response, history, past_key_values in model.stream_chat(tokenizer, input, history, past_key_values=past_key_values,
                                                                return_past_key_values=True,
                                                                max_length=max_length, top_p=top_p,
                                                                temperature=temperature):
        chatbot[-1] = (parse_text(input), parse_text(response))

        yield chatbot, history, past_key_values


def reset_user_input():
    return gr.update(value='')


def reset_state():
    return [], [], None


with gr.Blocks() as demo:
    gr.HTML("""<h1 align="center">ChatGLM2-6B</h1>""")

    chatbot = gr.Chatbot()
    with gr.Row():
        with gr.Column(scale=4):
            with gr.Column(scale=12):
                user_input = gr.Textbox(show_label=False, placeholder="Input...", lines=10).style(
                    container=False)
            with gr.Column(min_width=32, scale=1):
                submitBtn = gr.Button("Submit", variant="primary")
        with gr.Column(scale=1):
            emptyBtn = gr.Button("Clear History")
            max_length = gr.Slider(0, 32768, value=8192, step=1.0, label="Maximum length", interactive=True)
            top_p = gr.Slider(0, 1, value=0.8, step=0.01, label="Top P", interactive=True)
            temperature = gr.Slider(0, 1, value=0.95, step=0.01, label="Temperature", interactive=True)

    history = gr.State([])
    past_key_values = gr.State(None)

    submitBtn.click(predict, [user_input, chatbot, max_length, top_p, temperature, history, past_key_values],
                    [chatbot, history, past_key_values], show_progress=True)
    submitBtn.click(reset_user_input, [], [user_input])

    emptyBtn.click(reset_state, outputs=[chatbot, history, past_key_values], show_progress=True)

demo.queue().launch(share=False, inbrowser=True)```
以上为代码
以下为报错
```python
Some weights of ChatGLMForConditionalGeneration were not initialized from the model checkpoint at D:\chatglm\models\chatglm2-6b and are newly initialized: ['transformer.encoder.layers.2.self_attention.query_key_value.bias', 'transformer.encoder.layers.1.self_attention.dense.weight', 'transformer.encoder.layers.24.post_attention_layernorm.weight', 'transformer.encoder.layers.0.post_attention_layernorm.weight', 'transformer.encoder.layers.18.self_attention.query_key_value.weight', 'transformer.embedding.word_embeddings.weight', 'transformer.encoder.layers.0.self_attention.query_key_value.bias', 'transformer.encoder.layers.20.self_attention.dense.weight', 'transformer.encoder.layers.17.mlp.dense_h_to_4h.weight', 'transformer.encoder.layers.21.mlp.dense_4h_to_h.weight', 'transformer.encoder.layers.23.mlp.dense_h_to_4h.weight', 'transformer.rotary_pos_emb.inv_freq', 'transformer.encoder.layers.2.self_attention.dense.weight', 'transformer.encoder.layers.24.self_attention.dense.weight', 'transformer.encoder.layers.16.mlp.dense_4h_to_h.weight', 'transformer.encoder.layers.3.post_attention_layernorm.weight', 'transformer.encoder.layers.17.input_layernorm.weight', 'transformer.encoder.layers.27.self_attention.query_key_value.bias', 'transformer.encoder.layers.7.mlp.dense_4h_to_h.weight', 'transformer.encoder.layers.5.post_attention_layernorm.weight', 'transformer.encoder.layers.25.self_attention.query_key_value.bias', 'transformer.encoder.layers.15.mlp.dense_h_to_4h.weight', 'transformer.encoder.layers.6.self_attention.query_key_value.bias', 'transformer.encoder.layers.23.self_attention.query_key_value.bias', 'transformer.encoder.layers.11.self_attention.query_key_value.bias', 'transformer.encoder.layers.9.input_layernorm.weight', 'transformer.encoder.layers.12.input_layernorm.weight', 'transformer.encoder.layers.14.mlp.dense_4h_to_h.weight', 'transformer.encoder.layers.5.mlp.dense_4h_to_h.weight', 'transformer.encoder.layers.19.post_attention_layernorm.weight', 'transformer.encoder.layers.6.mlp.dense_4h_to_h.weight', 'transformer.encoder.layers.13.post_attention_layernorm.weight', 'transformer.encoder.layers.22.mlp.dense_4h_to_h.weight', 'transformer.encoder.layers.13.mlp.dense_4h_to_h.weight', 'transformer.encoder.layers.0.self_attention.dense.weight', 'transformer.encoder.layers.24.mlp.dense_4h_to_h.weight', 'transformer.encoder.layers.1.self_attention.query_key_value.weight', 'transformer.encoder.layers.13.self_attention.dense.weight', 'transformer.encoder.layers.17.mlp.dense_4h_to_h.weight', 'transformer.encoder.layers.25.mlp.dense_4h_to_h.weight', 'transformer.encoder.layers.8.input_layernorm.weight', 'transformer.output_layer.weight', 'transformer.encoder.layers.27.mlp.dense_h_to_4h.weight', 'transformer.encoder.layers.20.post_attention_layernorm.weight', 'transformer.encoder.layers.2.mlp.dense_h_to_4h.weight', 'transformer.encoder.layers.5.self_attention.query_key_value.weight', 'transformer.encoder.layers.19.input_layernorm.weight', 'transformer.encoder.layers.23.self_attention.dense.weight', 'transformer.encoder.layers.11.self_attention.query_key_value.weight', 'transformer.encoder.layers.23.mlp.dense_4h_to_h.weight', 'transformer.encoder.layers.13.input_layernorm.weight', 'transformer.encoder.layers.7.self_attention.query_key_value.weight', 'transformer.encoder.layers.19.self_attention.dense.weight', 'transformer.encoder.layers.16.self_attention.dense.weight', 'transformer.encoder.layers.8.mlp.dense_4h_to_h.weight', 'transformer.encoder.layers.5.mlp.dense_h_to_4h.weight', 'transformer.encoder.layers.4.self_attention.dense.weight', 'transformer.encoder.layers.0.mlp.dense_4h_to_h.weight', 'transformer.encoder.layers.8.self_attention.query_key_value.bias', 'transformer.encoder.layers.21.input_layernorm.weight', 'transformer.encoder.layers.25.input_layernorm.weight', 'transformer.encoder.layers.9.post_attention_layernorm.weight', 'transformer.encoder.layers.9.mlp.dense_h_to_4h.weight', 'transformer.encoder.layers.3.mlp.dense_h_to_4h.weight', 'transformer.encoder.layers.5.self_attention.dense.weight', 'transformer.encoder.layers.12.self_attention.dense.weight', 'transformer.encoder.layers.13.self_attention.query_key_value.weight', 'transformer.encoder.layers.16.mlp.dense_h_to_4h.weight', 'transformer.encoder.layers.27.self_attention.dense.weight', 'transformer.encoder.layers.14.mlp.dense_h_to_4h.weight', 'transformer.encoder.layers.25.mlp.dense_h_to_4h.weight', 'transformer.encoder.layers.1.mlp.dense_h_to_4h.weight', 'transformer.encoder.layers.25.post_attention_layernorm.weight', 'transformer.encoder.layers.4.post_attention_layernorm.weight', 'transformer.encoder.layers.6.mlp.dense_h_to_4h.weight', 'transformer.encoder.layers.19.mlp.dense_4h_to_h.weight', 'transformer.encoder.layers.27.input_layernorm.weight', 'transformer.encoder.layers.10.self_attention.query_key_value.weight', 'transformer.encoder.layers.20.mlp.dense_4h_to_h.weight', 'transformer.encoder.layers.20.input_layernorm.weight', 'transformer.encoder.layers.22.input_layernorm.weight', 'transformer.encoder.layers.7.mlp.dense_h_to_4h.weight', 'transformer.encoder.layers.1.mlp.dense_4h_to_h.weight', 'transformer.encoder.layers.0.input_layernorm.weight', 'transformer.encoder.layers.3.input_layernorm.weight', 'transformer.encoder.layers.3.mlp.dense_4h_to_h.weight', 'transformer.encoder.layers.9.mlp.dense_4h_to_h.weight', 'transformer.encoder.layers.10.mlp.dense_4h_to_h.weight', 'transformer.encoder.layers.27.mlp.dense_4h_to_h.weight', 'transformer.encoder.layers.3.self_attention.query_key_value.weight', 'transformer.encoder.layers.13.self_attention.query_key_value.bias', 'transformer.encoder.layers.8.self_attention.dense.weight', 'transformer.encoder.layers.14.self_attention.query_key_value.weight', 'transformer.encoder.layers.14.self_attention.dense.weight', 'transformer.encoder.layers.11.post_attention_layernorm.weight', 'transformer.encoder.layers.2.self_attention.query_key_value.weight', 'transformer.encoder.layers.24.mlp.dense_h_to_4h.weight', 'transformer.encoder.layers.26.mlp.dense_h_to_4h.weight', 'transformer.encoder.layers.7.self_attention.dense.weight', 'transformer.encoder.layers.26.self_attention.dense.weight', 'transformer.encoder.layers.21.post_attention_layernorm.weight', 'transformer.encoder.layers.7.post_attention_layernorm.weight', 'transformer.encoder.layers.16.self_attention.query_key_value.bias', 'transformer.encoder.layers.19.self_attention.query_key_value.weight', 'transformer.encoder.layers.26.input_layernorm.weight', 'transformer.encoder.layers.11.self_attention.dense.weight', 'transformer.encoder.layers.6.self_attention.dense.weight', 'transformer.encoder.layers.18.post_attention_layernorm.weight', 'transformer.encoder.layers.15.input_layernorm.weight', 'transformer.encoder.layers.25.self_attention.dense.weight', 'transformer.encoder.layers.0.mlp.dense_h_to_4h.weight', 'transformer.encoder.layers.5.self_attention.query_key_value.bias', 'transformer.encoder.layers.4.input_layernorm.weight', 'transformer.encoder.layers.27.self_attention.query_key_value.weight', 'transformer.encoder.layers.1.post_attention_layernorm.weight', 'transformer.encoder.layers.19.self_attention.query_key_value.bias', 'transformer.encoder.layers.25.self_attention.query_key_value.weight', 'transformer.encoder.layers.8.mlp.dense_h_to_4h.weight', 'transformer.encoder.layers.9.self_attention.dense.weight', 'transformer.encoder.layers.18.input_layernorm.weight', 'transformer.encoder.layers.22.self_attention.query_key_value.weight', 'transformer.encoder.layers.24.self_attention.query_key_value.weight', 'transformer.encoder.layers.20.mlp.dense_h_to_4h.weight', 'transformer.encoder.layers.5.input_layernorm.weight', 'transformer.encoder.layers.16.input_layernorm.weight', 'transformer.encoder.layers.27.post_attention_layernorm.weight', 'transformer.encoder.layers.4.mlp.dense_h_to_4h.weight', 'transformer.encoder.layers.9.self_attention.query_key_value.bias', 'transformer.encoder.layers.20.self_attention.query_key_value.weight', 'transformer.encoder.layers.22.self_attention.query_key_value.bias', 'transformer.encoder.layers.26.post_attention_layernorm.weight', 'transformer.encoder.layers.3.self_attention.query_key_value.bias', 'transformer.encoder.layers.10.input_layernorm.weight', 'transformer.encoder.layers.2.mlp.dense_4h_to_h.weight', 'transformer.encoder.layers.12.self_attention.query_key_value.bias', 'transformer.encoder.layers.17.self_attention.query_key_value.weight', 'transformer.encoder.layers.18.mlp.dense_h_to_4h.weight', 'transformer.encoder.layers.17.self_attention.query_key_value.bias', 'transformer.encoder.layers.18.mlp.dense_4h_to_h.weight', 'transformer.encoder.layers.2.post_attention_layernorm.weight', 'transformer.encoder.layers.23.post_attention_layernorm.weight', 'transformer.encoder.layers.14.input_layernorm.weight', 'transformer.encoder.layers.24.self_attention.query_key_value.bias', 'transformer.encoder.layers.13.mlp.dense_h_to_4h.weight', 'transformer.encoder.layers.11.input_layernorm.weight', 'transformer.encoder.layers.6.input_layernorm.weight', 'transformer.encoder.layers.12.post_attention_layernorm.weight', 'transformer.encoder.layers.12.mlp.dense_4h_to_h.weight', 'transformer.encoder.layers.15.self_attention.query_key_value.weight', 'transformer.encoder.layers.15.mlp.dense_4h_to_h.weight', 'transformer.encoder.layers.2.input_layernorm.weight', 'transformer.encoder.layers.8.post_attention_layernorm.weight', 'transformer.encoder.layers.18.self_attention.query_key_value.bias', 'transformer.encoder.layers.22.self_attention.dense.weight', 'transformer.encoder.layers.16.post_attention_layernorm.weight', 'transformer.encoder.layers.26.self_attention.query_key_value.weight', 'transformer.encoder.layers.22.post_attention_layernorm.weight', 'transformer.encoder.layers.6.post_attention_layernorm.weight', 'transformer.encoder.layers.8.self_attention.query_key_value.weight', 'transformer.encoder.layers.4.self_attention.query_key_value.weight', 'transformer.encoder.layers.23.input_layernorm.weight', 'transformer.encoder.layers.26.mlp.dense_4h_to_h.weight', 'transformer.encoder.layers.10.mlp.dense_h_to_4h.weight', 'transformer.encoder.layers.22.mlp.dense_h_to_4h.weight', 'transformer.encoder.layers.15.self_attention.dense.weight', 'transformer.encoder.layers.20.self_attention.query_key_value.bias', 'transformer.encoder.layers.10.post_attention_layernorm.weight', 'transformer.encoder.layers.4.mlp.dense_4h_to_h.weight', 'transformer.encoder.layers.14.self_attention.query_key_value.bias', 'transformer.encoder.layers.17.self_attention.dense.weight', 'transformer.encoder.layers.9.self_attention.query_key_value.weight', 'transformer.encoder.layers.23.self_attention.query_key_value.weight', 'transformer.encoder.layers.17.post_attention_layernorm.weight', 'transformer.encoder.layers.21.mlp.dense_h_to_4h.weight', 'transformer.encoder.layers.26.self_attention.query_key_value.bias', 'transformer.encoder.layers.24.input_layernorm.weight', 'transformer.encoder.layers.15.post_attention_layernorm.weight', 'transformer.encoder.layers.12.mlp.dense_h_to_4h.weight', 'transformer.encoder.layers.11.mlp.dense_4h_to_h.weight', 'transformer.encoder.layers.19.mlp.dense_h_to_4h.weight', 'transformer.encoder.layers.6.self_attention.query_key_value.weight', 'transformer.encoder.layers.7.self_attention.query_key_value.bias', 'transformer.encoder.layers.14.post_attention_layernorm.weight', 'transformer.encoder.layers.12.self_attention.query_key_value.weight', 'transformer.encoder.layers.21.self_attention.query_key_value.bias', 'transformer.encoder.layers.15.self_attention.query_key_value.bias', 'transformer.encoder.final_layernorm.weight', 'transformer.encoder.layers.21.self_attention.dense.weight', 'transformer.encoder.layers.18.self_attention.dense.weight', 'transformer.encoder.layers.7.input_layernorm.weight', 'transformer.encoder.layers.11.mlp.dense_h_to_4h.weight', 'transformer.encoder.layers.16.self_attention.query_key_value.weight', 'transformer.encoder.layers.0.self_attention.query_key_value.weight', 'transformer.encoder.layers.3.self_attention.dense.weight', 'transformer.encoder.layers.1.input_layernorm.weight', 'transformer.encoder.layers.10.self_attention.query_key_value.bias', 'transformer.encoder.layers.10.self_attention.dense.weight', 'transformer.encoder.layers.1.self_attention.query_key_value.bias', 'transformer.encoder.layers.21.self_attention.query_key_value.weight', 'transformer.encoder.layers.4.self_attention.query_key_value.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Traceback (most recent call last):
  File "D:\Programs Files\Python\Python311\Lib\site-packages\gradio\routes.py", line 393, in run_predict
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programs Files\Python\Python311\Lib\site-packages\gradio\blocks.py", line 1059, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programs Files\Python\Python311\Lib\site-packages\gradio\blocks.py", line 882, in call_function
    prediction = await anyio.to_thread.run_sync(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programs Files\Python\Python311\Lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programs Files\Python\Python311\Lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "D:\Programs Files\Python\Python311\Lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Programs Files\Python\Python311\Lib\site-packages\gradio\utils.py", line 549, in async_iteration
    return next(iterator)
           ^^^^^^^^^^^^^^
  File "D:\chatglm\web_demo_Muice.py", line 75, in predict
    for response, history, past_key_values in model.stream_chat(tokenizer, input, history, past_key_values=past_key_values,
                                                                ^^^^^^^^^
NameError: name 'tokenizer' is not defined

**Comment by homo11451419** [comment]
按照这篇文章方法，我（CUDA out of memory）了（显存足够大的可以试试）：https://zhuanlan.zhihu.com/p/645892136
（悲！！！）

**Comment by homo11451419** [comment]
成了吗？《 如 成 》
<img width="1280" alt="image" src="https://github.com/Moemu/Muice-Chatbot/assets/127638251/ab00e372-8f40-48fe-a5ae-55d96fdf186b">
