### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by MoeSnowyFox** [Moemu/Muice-Chatbot#25]
![image](https://github.com/Moemu/Muice-Chatbot/assets/156929726/58bedf9a-b219-4b72-8220-62d0a9235e7c)

登录pygocq后(使用安卓手表协议)可以正确收到消息 但是qq没有回复 同时cou和内存负载并不高 疑似模型未正常运行 请问是否需要提供其他log文件等

**Comment by Moemu** [comment]
可以使用下述代码块测试LLM，如果正常输出就说明模型没问题。
顺带一提，int4量化微调模型可能并不支持Chatglm2-6B，需要使用Chatglm2-6B-int4
```
model_path = "./model/chatglm2-6b-int4" #根据你实际情况更改模型目录
pt_model_path = "./model/Muice" #提示找不到文件把这两个目录改成绝对目录
if 'checkpoint-3000' in os.listdir(pt_model_path):
    pt_model_path = os.path.join(pt_model_path, 'checkpoint-3000')
config = AutoConfig.from_pretrained(model_path, trust_remote_code=True, pre_seq_len=128)
tokenizer = AutoTokenizer.from_pretrained(model_path, trust_remote_code=True)
model = AutoModel.from_pretrained(model_path, config=config, trust_remote_code=True).cpu()
prefix_state_dict = torch.load(os.path.join(pt_model_path, "pytorch_model.bin"),map_location='cpu'))
new_prefix_state_dict = {}
for k, v in prefix_state_dict.items():
    if k.startswith("transformer.prefix_encoder."):
        new_prefix_state_dict[k[len("transformer.prefix_encoder."):]] = v
model.transformer.prefix_encoder.load_state_dict(new_prefix_state_dict)
model.transformer.prefix_encoder.float()
model = model.eval()
print(model.ask("你好"))
```

**Comment by MoeSnowyFox** [comment]
使用/help  qq有正确回复 但是加载模型阶段有输出Some weights of ChatGLMForConditionalGeneration were not initialized from the model checkpoint at model/chatglm2-6b and are newly initialized: ['transformer.prefix_encoder.embedding.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
并无其他输出

**Comment by MoeSnowyFox** [comment]
(使用2.2版本的非int4版本微调模型)

**Comment by MoeSnowyFox** [comment]
请问是否有 运行微调版本glm2-6b的api_demo.py的直接运行版本 或相关文档 (因为网络上只找到了有关微调模型的教程 并无运行微调的方法) 感谢大佬

**Comment by Moemu** [comment]
这是正常输出,我加载都会有
________________________________
发件人: SnowyFox ***@***.***>
发送时间: 2024年3月17日 20:26
收件人: Moemu/Muice-Chatbot ***@***.***>
抄送: Moemu ***@***.***>; Comment ***@***.***>
主题: Re: [Moemu/Muice-Chatbot] [Bug] (Issue #25)


使用/help qq有正确回复 但是加载模型阶段有输出Some weights of ChatGLMForConditionalGeneration were not initialized from the model checkpoint at model/chatglm2-6b and are newly initialized: ['transformer.prefix_encoder.embedding.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
并无其他输出

―

**Comment by Moemu** [comment]
多了解repo里的文件可以帮助你解决问题: https://github.com/Moemu/Muice-Chatbot/blob/main/api.py
________________________________
发件人: SnowyFox ***@***.***>
发送时间: 2024年3月18日 23:28
收件人: Moemu/Muice-Chatbot ***@***.***>
抄送: Moemu ***@***.***>; Comment ***@***.***>
主题: Re: [Moemu/Muice-Chatbot] [Bug] (Issue #25)


请问是否有 运行微调版本glm2-6b的api_demo.py的直接运行版本 或相关文档 (因为网络上只找到了有关微调模型的教程 并无运行微调的方法) 感谢大佬

―

**Comment by MoeSnowyFox** [comment]
报错为Traceback (most recent call last):
  File "C:\Users\UserAdmin\.conda\envs\muice3\lib\site-packages\flask\app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\UserAdmin\.conda\envs\muice3\lib\site-packages\flask\app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\UserAdmin\.conda\envs\muice3\lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\UserAdmin\.conda\envs\muice3\lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "f:\chat\muice\Muice-Chatbot\qqbot2.py", line 31, in add_post
    reply = muice.ask(text=mess, user_qq=sender_user_id)
  File "f:\chat\muice\Muice-Chatbot\Muice.py", line 35, in ask
    self.reply = self.model.ask(self.user_text, self.history)
  File "f:\chat\muice\Muice-Chatbot\llm\chatglm2.py", line 30, in ask
    response, _ = self.model.chat(self.tokenizer, user_text, history=history)
  File "C:\Users\UserAdmin\.conda\envs\muice3\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\UserAdmin/.cache\huggingface\modules\transformers_modules\chatglm2-6b\modeling_chatglm.py", line 1026, in chat
    outputs = self.generate(**inputs, **gen_kwargs)
  File "C:\Users\UserAdmin\.conda\envs\muice3\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\UserAdmin\.conda\envs\muice3\lib\site-packages\transformers\generation\utils.py", line 1588, in generate
    return self.sample(
  File "C:\Users\UserAdmin\.conda\envs\muice3\lib\site-packages\transformers\generation\utils.py", line 2642, in sample
    outputs = self(
  File "C:\Users\UserAdmin\.conda\envs\muice3\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\UserAdmin/.cache\huggingface\modules\transformers_modules\chatglm2-6b\modeling_chatglm.py", line 931, in forward
    transformer_outputs = self.transformer(
  File "C:\Users\UserAdmin\.conda\envs\muice3\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\UserAdmin/.cache\huggingface\modules\transformers_modules\chatglm2-6b\modeling_chatglm.py", line 824, in forward
    hidden_states, presents, all_hidden_states, all_self_attentions = self.encoder(
  File "C:\Users\UserAdmin\.conda\envs\muice3\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\UserAdmin/.cache\huggingface\modules\transformers_modules\chatglm2-6b\modeling_chatglm.py", line 634, in forward
    layer_ret = layer(
  File "C:\Users\UserAdmin\.conda\envs\muice3\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\UserAdmin/.cache\huggingface\modules\transformers_modules\chatglm2-6b\modeling_chatglm.py", line 538, in forward
    attention_output, kv_cache = self.self_attention(
  File "C:\Users\UserAdmin\.conda\envs\muice3\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\UserAdmin/.cache\huggingface\modules\transformers_modules\chatglm2-6b\modeling_chatglm.py", line 372, in forward
    mixed_x_layer = self.query_key_value(hidden_states)
  File "C:\Users\UserAdmin\.conda\envs\muice3\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\UserAdmin\.conda\envs\muice3\lib\site-packages\torch\nn\modules\linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: "addmm_impl_cpu_" not implemented for 'Half'还是因为cpu问题

**Comment by MoeSnowyFox** [comment]
于chatglm2.py行19应修改为  model = AutoModel.from_pretrained(model_path, config=config, trust_remote_code=True).float()方可正常运行
