### ISSUE TITLE
[Bug] 求助，运行问题

### ISSUE THREAD

**Issue by XHQian** [Moemu/Muice-Chatbot#43]
### 描述此Bug

无法回复消息，出现以下报错：

ValueError: too many values to unpack (expected 2)

apscheduler.schedulers.SchedulerAlreadyRunningError: Scheduler is already running

### 控制台输出

(Muice) PS D:\Project\Muice-Chatbot> python main.py
[WARNING] Load parallel cpu kernel failed C:\Users\XuHuiQian\.cache\huggingface\modules\transformers_modules\chatglm2-6b-int4\quantization_kernels_parallel.so: Traceback (most recent call last):
  File "C:\Users\XuHuiQian\.cache\huggingface\modules\transformers_modules\chatglm2-6b-int4\quantization.py", line 148, in __init__
    kernels = ctypes.cdll.LoadLibrary(kernel_file)
  File "D:\Miniconda\envs\Muice\lib\ctypes\__init__.py", line 452, in LoadLibrary
    return self._dlltype(name)
  File "D:\Miniconda\envs\Muice\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'C:\Users\XuHuiQian\.cache\huggingface\modules\transformers_modules\chatglm2-6b-int4\quantization_kernels_parallel.so' (or one of its dependencies). Try using the full path with constructor syntax.

Some weights of ChatGLMForConditionalGeneration were not initialized from the model checkpoint at D:\Project\Muice-Chatbot\model\chatglm2-6b-int4 and are newly initialized: ['transformer.prefix_encoder.embedding.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
D:\Project\Muice-Chatbot\llm\transformers.py:17: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  prefix_state_dict = torch.load(os.path.join(pt_model_path, "pytorch_model.bin"),map_location='cpu')
Traceback (most recent call last):
  File "D:\Project\Muice-Chatbot\main.py", line 18, in <module>
    model = model.llm('D:\Project\Muice-Chatbot\model\chatglm2-6b-int4','.D:\Project\Muice-Chatbot\model\Muice')
  File "D:\Project\Muice-Chatbot\llm\transformers.py", line 17, in __init__
    prefix_state_dict = torch.load(os.path.join(pt_model_path, "pytorch_model.bin"),map_location='cpu')
  File "D:\Miniconda\envs\Muice\lib\site-packages\torch\serialization.py", line 1185, in load
    with _open_file_like(f, "rb") as opened_file:
  File "D:\Miniconda\envs\Muice\lib\site-packages\torch\serialization.py", line 562, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "D:\Miniconda\envs\Muice\lib\site-packages\torch\serialization.py", line 543, in __init__
    super().__init__(open(name, mode))
OSError: [Errno 22] Invalid argument: '.D:\\Project\\Muice-Chatbot\\model\\Muice\\pytorch_model.bin'
(Muice) PS D:\Project\Muice-Chatbot> python main.py
[WARNING] Load parallel cpu kernel failed C:\Users\XuHuiQian\.cache\huggingface\modules\transformers_modules\chatglm2-6b-int4\quantization_kernels_parallel.so: Traceback (most recent call last):
  File "C:\Users\XuHuiQian\.cache\huggingface\modules\transformers_modules\chatglm2-6b-int4\quantization.py", line 148, in __init__
    kernels = ctypes.cdll.LoadLibrary(kernel_file)
  File "D:\Miniconda\envs\Muice\lib\ctypes\__init__.py", line 452, in LoadLibrary
    return self._dlltype(name)
  File "D:\Miniconda\envs\Muice\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'C:\Users\XuHuiQian\.cache\huggingface\modules\transformers_modules\chatglm2-6b-int4\quantization_kernels_parallel.so' (or one of its dependencies). Try using the full path with constructor syntax.

Some weights of ChatGLMForConditionalGeneration were not initialized from the model checkpoint at D:\Project\Muice-Chatbot\model\chatglm2-6b-int4 and are newly initialized: ['transformer.prefix_encoder.embedding.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
D:\Project\Muice-Chatbot\llm\transformers.py:17: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  prefix_state_dict = torch.load(os.path.join(pt_model_path, "pytorch_model.bin"),map_location='cpu')
[INFO] Adding job tentatively -- it will be properly scheduled when the scheduler starts
INFO:     Started server process [12632]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:21050 (Press CTRL+C to quit)
INFO:     ('127.0.0.1', 13287) - "WebSocket /ws/api" [accepted]
[INFO] Added job "QQBot.timework" to job store "default"
[INFO] Scheduler started
INFO:     connection open
[INFO] 已链接
[INFO] 收到____的消息：2
C:\Users\XuHuiQian\.cache\huggingface\modules\transformers_modules\chatglm2-6b-int4\modeling_chatglm.py:228: UserWarning: 1Torch was not compiled with flash attention. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp:566.)
  context_layer = torch.nn.functional.scaled_dot_product_attention(query_layer, key_layer, value_layer,
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "D:\Miniconda\envs\Muice\lib\site-packages\uvicorn\protocols\websockets\websockets_impl.py", line 244, in run_asgi
    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)  # type: ignore[func-returns-value]
  File "D:\Miniconda\envs\Muice\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
  File "D:\Miniconda\envs\Muice\lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "D:\Miniconda\envs\Muice\lib\site-packages\starlette\applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\Miniconda\envs\Muice\lib\site-packages\starlette\middleware\errors.py", line 151, in __call__
    await self.app(scope, receive, send)
  File "D:\Miniconda\envs\Muice\lib\site-packages\starlette\middleware\exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "D:\Miniconda\envs\Muice\lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "D:\Miniconda\envs\Muice\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "D:\Miniconda\envs\Muice\lib\site-packages\starlette\routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\Miniconda\envs\Muice\lib\site-packages\starlette\routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "D:\Miniconda\envs\Muice\lib\site-packages\starlette\routing.py", line 373, in handle
    await self.app(scope, receive, send)
  File "D:\Miniconda\envs\Muice\lib\site-packages\starlette\routing.py", line 96, in app
    await wrap_app_handling_exceptions(app, session)(scope, receive, send)
  File "D:\Miniconda\envs\Muice\lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "D:\Miniconda\envs\Muice\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "D:\Miniconda\envs\Muice\lib\site-packages\starlette\routing.py", line 94, in app
    await func(session)
  File "D:\Miniconda\envs\Muice\lib\site-packages\fastapi\routing.py", line 348, in app
    await dependant.call(**values)
  File "D:\Project\Muice-Chatbot\ws.py", line 46, in websocket_endpoint
    reply = await self.processing_json(data)
  File "D:\Project\Muice-Chatbot\ws.py", line 72, in processing_json
    reply_message = await self.produce_reply(message, sender_user_id)
  File "D:\Project\Muice-Chatbot\ws.py", line 102, in produce_reply
    reply = self.muice_app.ask(text=mess, user_qq=sender_user_id)
  File "D:\Project\Muice-Chatbot\Muice.py", line 31, in ask
    self.reply = self.model.ask(self.user_text, self.history)
  File "D:\Project\Muice-Chatbot\llm\transformers.py", line 27, in ask
    response, _ = self.model.chat(self.tokenizer, user_text, history=history)
  File "D:\Miniconda\envs\Muice\lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\XuHuiQian\.cache\huggingface\modules\transformers_modules\chatglm2-6b-int4\modeling_chatglm.py", line 1026, in chat
    outputs = self.generate(**inputs, **gen_kwargs)
  File "D:\Miniconda\envs\Muice\lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "D:\Miniconda\envs\Muice\lib\site-packages\transformers\generation\utils.py", line 1914, in generate
    result = self._sample(
  File "D:\Miniconda\envs\Muice\lib\site-packages\transformers\generation\utils.py", line 2651, in _sample
    outputs = self(
  File "D:\Miniconda\envs\Muice\lib\site-packages\torch\nn\modules\module.py", line 1716, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\Miniconda\envs\Muice\lib\site-packages\torch\nn\modules\module.py", line 1727, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\XuHuiQian\.cache\huggingface\modules\transformers_modules\chatglm2-6b-int4\modeling_chatglm.py", line 931, in forward
    transformer_outputs = self.transformer(
  File "D:\Miniconda\envs\Muice\lib\site-packages\torch\nn\modules\module.py", line 1716, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\Miniconda\envs\Muice\lib\site-packages\torch\nn\modules\module.py", line 1727, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\XuHuiQian\.cache\huggingface\modules\transformers_modules\chatglm2-6b-int4\modeling_chatglm.py", line 824, in forward
    hidden_states, presents, all_hidden_states, all_self_attentions = self.encoder(
  File "D:\Miniconda\envs\Muice\lib\site-packages\torch\nn\modules\module.py", line 1716, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\Miniconda\envs\Muice\lib\site-packages\torch\nn\modules\module.py", line 1727, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\XuHuiQian\.cache\huggingface\modules\transformers_modules\chatglm2-6b-int4\modeling_chatglm.py", line 634, in forward
    layer_ret = layer(
  File "D:\Miniconda\envs\Muice\lib\site-packages\torch\nn\modules\module.py", line 1716, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\Miniconda\envs\Muice\lib\site-packages\torch\nn\modules\module.py", line 1727, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\XuHuiQian\.cache\huggingface\modules\transformers_modules\chatglm2-6b-int4\modeling_chatglm.py", line 538, in forward
    attention_output, kv_cache = self.self_attention(
  File "D:\Miniconda\envs\Muice\lib\site-packages\torch\nn\modules\module.py", line 1716, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\Miniconda\envs\Muice\lib\site-packages\torch\nn\modules\module.py", line 1727, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\XuHuiQian\.cache\huggingface\modules\transformers_modules\chatglm2-6b-int4\modeling_chatglm.py", line 409, in forward
    cache_k, cache_v = kv_cache
ValueError: too many values to unpack (expected 2)
INFO:     connection closed
INFO:     ('127.0.0.1', 13295) - "WebSocket /ws/api" [accepted]
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "D:\Miniconda\envs\Muice\lib\site-packages\uvicorn\protocols\websockets\websockets_impl.py", line 244, in run_asgi
    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)  # type: ignore[func-returns-value]
  File "D:\Miniconda\envs\Muice\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
  File "D:\Miniconda\envs\Muice\lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "D:\Miniconda\envs\Muice\lib\site-packages\starlette\applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\Miniconda\envs\Muice\lib\site-packages\starlette\middleware\errors.py", line 151, in __call__
    await self.app(scope, receive, send)
  File "D:\Miniconda\envs\Muice\lib\site-packages\starlette\middleware\exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "D:\Miniconda\envs\Muice\lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "D:\Miniconda\envs\Muice\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "D:\Miniconda\envs\Muice\lib\site-packages\starlette\routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\Miniconda\envs\Muice\lib\site-packages\starlette\routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "D:\Miniconda\envs\Muice\lib\site-packages\starlette\routing.py", line 373, in handle
    await self.app(scope, receive, send)
  File "D:\Miniconda\envs\Muice\lib\site-packages\starlette\routing.py", line 96, in app
    await wrap_app_handling_exceptions(app, session)(scope, receive, send)
  File "D:\Miniconda\envs\Muice\lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "D:\Miniconda\envs\Muice\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "D:\Miniconda\envs\Muice\lib\site-packages\starlette\routing.py", line 94, in app
    await func(session)
  File "D:\Miniconda\envs\Muice\lib\site-packages\fastapi\routing.py", line 348, in app
    await dependant.call(**values)
  File "D:\Project\Muice-Chatbot\ws.py", line 40, in websocket_endpoint
    self.scheduler.start()
  File "D:\Miniconda\envs\Muice\lib\site-packages\apscheduler\schedulers\asyncio.py", line 37, in start
    super(AsyncIOScheduler, self).start(paused)
  File "D:\Miniconda\envs\Muice\lib\site-packages\apscheduler\schedulers\base.py", line 153, in start
    raise SchedulerAlreadyRunningError
apscheduler.schedulers.SchedulerAlreadyRunningError: Scheduler is already running
INFO:     connection open
INFO:     connection closed

### 复现该Bug的操作

信任的qq发给机器人qq消息时就会一直出现apscheduler.schedulers.SchedulerAlreadyRunningError: Scheduler is already running

**Comment by Moemu** [comment]
你是不是改了main.py，main.py的第18行的第二个路径有问题，前面多了一个点

**Comment by XHQian** [comment]
```bash
(Muice) PS D:\Project\Muice-Chatbot> & D:/Miniconda/envs/Muice/python.exe d:/Project/Muice-Chatbot/main.py
[WARNING] Load parallel cpu kernel failed C:\Users\XuHuiQian\.cache\huggingface\modules\transformers_modules\chatglm2-6b-int4\quantization_kernels_parallel.so: Traceback (most recent call last):
  File "C:\Users\XuHuiQian\.cache\huggingface\modules\transformers_modules\chatglm2-6b-int4\quantization.py", line 148, in __init__
    kernels = ctypes.cdll.LoadLibrary(kernel_file)
  File "D:\Miniconda\envs\Muice\lib\ctypes\__init__.py", line 452, in LoadLibrary
    return self._dlltype(name)
  File "D:\Miniconda\envs\Muice\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'C:\Users\XuHuiQian\.cache\huggingface\modules\transformers_modules\chatglm2-6b-int4\quantization_kernels_parallel.so' (or one of its dependencies). Try using the full path with constructor syntax.

Some weights of ChatGLMForConditionalGeneration were not initialized from the model checkpoint at D:\Project\Muice-Chatbot\model\chatglm2-6b-int4 and are newly initialized: ['transformer.prefix_encoder.embedding.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
d:\Project\Muice-Chatbot\llm\transformers.py:17: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  prefix_state_dict = torch.load(os.path.join(pt_model_path, "pytorch_model.bin"),map_location='cpu')
[INFO] Adding job tentatively -- it will be properly scheduled when the scheduler starts
INFO:     Started server process [21524]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:21050 (Press CTRL+C to quit)
INFO:     ('127.0.0.1', 1149) - "WebSocket /ws/api" [accepted]
[INFO] Added job "QQBot.timework" to job store "default"
[INFO] Scheduler started
INFO:     connection open
[INFO] 已链接
[INFO] 收到__的消息：11
C:\Users\XuHuiQian\.cache\huggingface\modules\transformers_modules\chatglm2-6b-int4\modeling_chatglm.py:228: UserWarning: 1Torch was not compiled with flash attention. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp:566.)
  context_layer = torch.nn.functional.scaled_dot_product_attention(query_layer, key_layer, value_layer,
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "D:\Miniconda\envs\Muice\lib\site-packages\uvicorn\protocols\websockets\websockets_impl.py", line 244, in run_asgi
    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)  # type: ignore[func-returns-value]
  File "D:\Miniconda\envs\Muice\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
  File "D:\Miniconda\envs\Muice\lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "D:\Miniconda\envs\Muice\lib\site-packages\starlette\applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\Miniconda\envs\Muice\lib\site-packages\starlette\middleware\errors.py", line 151, in __call__
    await self.app(scope, receive, send)
  File "D:\Miniconda\envs\Muice\lib\site-packages\starlette\middleware\exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "D:\Miniconda\envs\Muice\lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "D:\Miniconda\envs\Muice\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "D:\Miniconda\envs\Muice\lib\site-packages\starlette\routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\Miniconda\envs\Muice\lib\site-packages\starlette\routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "D:\Miniconda\envs\Muice\lib\site-packages\starlette\routing.py", line 373, in handle
    await self.app(scope, receive, send)
  File "D:\Miniconda\envs\Muice\lib\site-packages\starlette\routing.py", line 96, in app
    await wrap_app_handling_exceptions(app, session)(scope, receive, send)
  File "D:\Miniconda\envs\Muice\lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "D:\Miniconda\envs\Muice\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "D:\Miniconda\envs\Muice\lib\site-packages\starlette\routing.py", line 94, in app
    await func(session)
  File "D:\Miniconda\envs\Muice\lib\site-packages\fastapi\routing.py", line 348, in app
    await dependant.call(**values)
  File "d:\Project\Muice-Chatbot\ws.py", line 46, in websocket_endpoint
    reply = await self.processing_json(data)
  File "d:\Project\Muice-Chatbot\ws.py", line 72, in processing_json
    reply_message = await self.produce_reply(message, sender_user_id)
  File "d:\Project\Muice-Chatbot\ws.py", line 102, in produce_reply
    reply = self.muice_app.ask(text=mess, user_qq=sender_user_id)
  File "d:\Project\Muice-Chatbot\Muice.py", line 31, in ask
    self.reply = self.model.ask(self.user_text, self.history)
  File "d:\Project\Muice-Chatbot\llm\transformers.py", line 27, in ask
    response, _ = self.model.chat(self.tokenizer, user_text, history=history)
  File "D:\Miniconda\envs\Muice\lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\XuHuiQian\.cache\huggingface\modules\transformers_modules\chatglm2-6b-int4\modeling_chatglm.py", line 1026, in chat
    outputs = self.generate(**inputs, **gen_kwargs)
  File "D:\Miniconda\envs\Muice\lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "D:\Miniconda\envs\Muice\lib\site-packages\transformers\generation\utils.py", line 1914, in generate
    result = self._sample(
  File "D:\Miniconda\envs\Muice\lib\site-packages\transformers\generation\utils.py", line 2651, in _sample
    outputs = self(
  File "D:\Miniconda\envs\Muice\lib\site-packages\torch\nn\modules\module.py", line 1716, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\Miniconda\envs\Muice\lib\site-packages\torch\nn\modules\module.py", line 1727, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\XuHuiQian\.cache\huggingface\modules\transformers_modules\chatglm2-6b-int4\modeling_chatglm.py", line 931, in forward
    transformer_outputs = self.transformer(
  File "D:\Miniconda\envs\Muice\lib\site-packages\torch\nn\modules\module.py", line 1716, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\Miniconda\envs\Muice\lib\site-packages\torch\nn\modules\module.py", line 1727, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\XuHuiQian\.cache\huggingface\modules\transformers_modules\chatglm2-6b-int4\modeling_chatglm.py", line 824, in forward
    hidden_states, presents, all_hidden_states, all_self_attentions = self.encoder(
  File "D:\Miniconda\envs\Muice\lib\site-packages\torch\nn\modules\module.py", line 1716, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\Miniconda\envs\Muice\lib\site-packages\torch\nn\modules\module.py", line 1727, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\XuHuiQian\.cache\huggingface\modules\transformers_modules\chatglm2-6b-int4\modeling_chatglm.py", line 634, in forward
    layer_ret = layer(
  File "D:\Miniconda\envs\Muice\lib\site-packages\torch\nn\modules\module.py", line 1716, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\Miniconda\envs\Muice\lib\site-packages\torch\nn\modules\module.py", line 1727, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\XuHuiQian\.cache\huggingface\modules\transformers_modules\chatglm2-6b-int4\modeling_chatglm.py", line 538, in forward
    attention_output, kv_cache = self.self_attention(
  File "D:\Miniconda\envs\Muice\lib\site-packages\torch\nn\modules\module.py", line 1716, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\Miniconda\envs\Muice\lib\site-packages\torch\nn\modules\module.py", line 1727, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\XuHuiQian\.cache\huggingface\modules\transformers_modules\chatglm2-6b-int4\modeling_chatglm.py", line 409, in forward
    cache_k, cache_v = kv_cache
ValueError: too many values to unpack (expected 2)
INFO:     connection closed
INFO:     ('127.0.0.1', 1155) - "WebSocket /ws/api" [accepted]
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "D:\Miniconda\envs\Muice\lib\site-packages\uvicorn\protocols\websockets\websockets_impl.py", line 244, in run_asgi
    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)  # type: ignore[func-returns-value]
  File "D:\Miniconda\envs\Muice\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
  File "D:\Miniconda\envs\Muice\lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "D:\Miniconda\envs\Muice\lib\site-packages\starlette\applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\Miniconda\envs\Muice\lib\site-packages\starlette\middleware\errors.py", line 151, in __call__
    await self.app(scope, receive, send)
  File "D:\Miniconda\envs\Muice\lib\site-packages\starlette\middleware\exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "D:\Miniconda\envs\Muice\lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "D:\Miniconda\envs\Muice\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "D:\Miniconda\envs\Muice\lib\site-packages\starlette\routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\Miniconda\envs\Muice\lib\site-packages\starlette\routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "D:\Miniconda\envs\Muice\lib\site-packages\starlette\routing.py", line 373, in handle
    await self.app(scope, receive, send)
  File "D:\Miniconda\envs\Muice\lib\site-packages\starlette\routing.py", line 96, in app
    await wrap_app_handling_exceptions(app, session)(scope, receive, send)
  File "D:\Miniconda\envs\Muice\lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "D:\Miniconda\envs\Muice\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "D:\Miniconda\envs\Muice\lib\site-packages\starlette\routing.py", line 94, in app
    await func(session)
  File "D:\Miniconda\envs\Muice\lib\site-packages\fastapi\routing.py", line 348, in app
    await dependant.call(**values)
  File "d:\Project\Muice-Chatbot\ws.py", line 40, in websocket_endpoint
    self.scheduler.start()
  File "D:\Miniconda\envs\Muice\lib\site-packages\apscheduler\schedulers\asyncio.py", line 37, in start
    super(AsyncIOScheduler, self).start(paused)
  File "D:\Miniconda\envs\Muice\lib\site-packages\apscheduler\schedulers\base.py", line 153, in start
    raise SchedulerAlreadyRunningError
apscheduler.schedulers.SchedulerAlreadyRunningError: Scheduler is already running
```

用原来的config里的会报错，改完之后还是这两个报错，这是文件结构
![image](https://github.com/user-attachments/assets/01562409-e19e-4eb3-8b86-da38c09f7545)

**Comment by XHQian** [comment]
```
(Muice) PS D:\Project\Muice-Chatbot> pip list
Package            Version
------------------ ------------------------
annotated-types    0.7.0
anyio              4.4.0
APScheduler        3.10.4
certifi            2024.7.4
charset-normalizer 3.3.2
click              8.1.7
colorama           0.4.6
cpm-kernels        1.0.11
dnspython          2.6.1
email_validator    2.2.0
exceptiongroup     1.2.2
fastapi            0.111.1
fastapi-cli        0.0.4
filelock           3.15.4
fsspec             2024.6.1
h11                0.14.0
httpcore           1.0.5
httptools          0.6.1
httpx              0.27.0
huggingface-hub    0.23.4
idna               3.7
intel-openmp       2021.4.0
Jinja2             3.1.4
markdown-it-py     3.0.0
MarkupSafe         2.1.5
mdurl              0.1.2
mkl                2021.4.0
modelscope         1.16.0
mpmath             1.3.0
networkx           3.3
numpy              1.26.4
packaging          24.1
Pillow             9.3.0
pip                24.0
pydantic           2.8.2
pydantic_core      2.20.1
Pygments           2.18.0
python-dotenv      1.0.1
python-multipart   0.0.9
pytz               2024.1
PyYAML             6.0.1
regex              2024.5.15
requests           2.32.3
rich               13.7.1
safetensors        0.4.3
sentencepiece      0.2.0
setuptools         69.5.1
shellingham        1.5.4
six                1.16.0
sniffio            1.3.1
starlette          0.37.2
sympy              1.13.0
tbb                2021.13.0
tokenizers         0.19.1
torch              2.5.0.dev20240713+cu124
torchaudio         2.4.0.dev20240714+cu124
torchvision        0.20.0.dev20240714+cu124
tqdm               4.66.4
transformers       4.42.4
typer              0.12.3
typing_extensions  4.12.2
tzdata             2024.1
tzlocal            5.2
urllib3            2.2.2
uvicorn            0.30.1
watchfiles         0.22.0
websockets         12.0
wheel              0.43.0
```

**Comment by MoeSnowyFox** [comment]
请问你使用的是cpu还是gpu运行chatglm2-6b-int4

**Comment by XHQian** [comment]
gpu



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年7月15日(周一) 晚上11:39
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Moemu/Muice-Chatbot] [Bug] 求助，运行问题 (Issue #43)




 
请问你使用的是cpu还是gpu运行chatglm2-6b-int4

**Comment by Moemu** [comment]
transformers版本号太高了，试着降级到4.30.2

**Comment by XHQian** [comment]
可以了，感谢

**Comment by XHQian** [comment]
不过好像不会主动发消息，请问有解决办法吗

**Comment by Moemu** [comment]
在默认配置的情况下，在bot启动一小时以后，bot会每一分钟以0.3%的概率尝试生成新话题并发起对话；如果要测试主动发起对话功能，你可以将`known_topic_probability`改成1，然后更改`ws.py`的[L27](https://github.com/Moemu/Muice-Chatbot/blob/d543ee005c513b09479fc8d9b1231fbc19763ad3/ws.py#L27C13-L27C82)为：
```python
self.time_dict = {qq_id: 0.0 for qq_id in self.trust_qq_list}
```

**Comment by XHQian** [comment]
感谢回答
