### ISSUE TITLE
[Bug]主动创建新对话功能奇妙问题

### ISSUE THREAD

**Issue by Tz-WIND** [Moemu/Muice-Chatbot#51]
### 描述此Bug

一旦开始创建新对话就会有这个报错

### 控制台输出

[ERROR] Job "QQBot.time_work (trigger: interval[0:01:00], next run at: 2024-08-31 11:48:03 CST)" raised an exception
Traceback (most recent call last):
  File "C:\Users\asus\anaconda3\envs\Muice\lib\site-packages\apscheduler\executors\base_py3.py", line 30, in run_coroutine_job
    retval = await job.func(*job.args, **job.kwargs)
  File "C:\Users\asus\Muice-Chatbot\ws.py", line 220, in time_work
    topic = self.muice_app.CreateANewTopic(value)
AttributeError: 'Muice' object has no attribute 'CreateANewTopic'. Did you mean: 'create_a_new_topic'?

### 额外信息
所有的库都是齐全的，torch版本2.3.0
只要不适用创建新对话功能即可正常运行

**Comment by MoeSnowyFox** [comment]
修了 这么抽象的bug我是怎么写出来的

**Comment by Tz-WIND** [comment]
蚌埠住了，什么原因导致的
